# Generated by Django 5.0.8 on 2024-12-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_alter_thing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thing_images/'),
        ),
    ]
