# Generated by Django 5.0.8 on 2024-12-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0004_alter_thing_featured_alter_thing_internal_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thing',
            name='internal_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='thing',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
