# Generated by Django 5.0.8 on 2025-01-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0007_thing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='png_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
