# Generated by Django 5.0.8 on 2025-01-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0008_thing_png_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='png_string',
        ),
    ]
