# Generated by Django 5.0.8 on 2025-01-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0009_remove_thing_png_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='image_alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
