# Generated by Django 5.0.8 on 2025-11-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0010_thing_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='custom_card',
            field=models.BooleanField(default=False),
        ),
    ]
