# Generated by Django 5.0.8 on 2024-11-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_place_slug_place_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type_list',
            field=models.ManyToManyField(blank=True, related_name='places', to='places.placetype'),
        ),
    ]
