# Generated by Django 5.0.8 on 2024-12-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_filter_subtype_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
