# Generated by Django 5.0.8 on 2024-12-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
