# Generated by Django 5.0.8 on 2025-01-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
