# Generated by Django 5.0.8 on 2024-12-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('featured', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('all_cities', 'All Cities'), ('cameron', 'Cameron'), ('gower', 'Gower'), ('holt', 'Holt'), ('lathrop', 'Lathrop'), ('lawson', 'Lawson'), ('osborn', 'Osborn'), ('plattsburg', 'Plattsburg'), ('trimble', 'Trimble'), ('turney', 'Turney')], default='all_cities', max_length=100)),
                ('image', models.ImageField(default='img/default_img_4x3.avif', upload_to='event_images/')),
                ('external_link', models.URLField(blank=True)),
                ('internal_page', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
