# Generated by Django 5.0.8 on 2025-01-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
