# Generated by Django 5.0.8 on 2025-01-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_image'),
        ('things', '0007_thing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='filter_type_list',
            field=models.ManyToManyField(blank=True, related_name='event_type_filters', to='things.filtertype'),
        ),
    ]
