# Generated by Django 5.0.8 on 2025-06-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_filter_type_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
