# Generated by Django 5.0.8 on 2026-04-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='internal_url',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
