# Generated by Django 5.0.8 on 2024-12-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('featured', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(choices=[('all_cities', 'All Cities'), ('cameron', 'Cameron'), ('gower', 'Gower'), ('holt', 'Holt'), ('lathrop', 'Lathrop'), ('lawson', 'Lawson'), ('osborn', 'Osborn'), ('plattsburg', 'Plattsburg'), ('trimble', 'Trimble'), ('turney', 'Turney')], default='all_cities', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('external_website', models.URLField(blank=True, null=True)),
                ('internal_page', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(default='img/default_img_4x3.avif', upload_to='resource_images/')),
                ('operation_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filter_subtype_list', models.ManyToManyField(blank=True, related_name='resource_subtype_filters', to='things.filtersubtype')),
                ('filter_type_list', models.ManyToManyField(blank=True, related_name='resource_type_filters', to='things.filtertype')),
            ],
        ),
    ]
