# Generated by Django 5.0.8 on 2026-04-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_resource_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='custom_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='image_alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='places_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='things_page',
            field=models.BooleanField(default=False),
        ),
    ]
