# Generated by Django 5.0.8 on 2026-04-22 06:25

from django.db import migrations

def migrate_data(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    # OLD MODELS
    Thing = apps.get_model('things', 'Thing')
    Place = apps.get_model('places', 'Place')

    # NEW MODEL
    Resource = apps.get_model('resources', 'Resource')

    # -----------------------------
    # 1. MIGRATE THINGS → RESOURCES
    # -----------------------------
    for thing in Thing.objects.using(db_alias).all():
        resource = Resource.objects.using(db_alias).create(
            name = thing.name,
            slug = thing.slug,
            featured=thing.featured,
            description=thing.description,
            address=thing.address,
            city=thing.city,
            state='MO',  # default since Thing didn’t have state
            phone_number=thing.phone_number,
            external_website=thing.external_website,
            internal_page=thing.internal_page,
            custom_card=thing.custom_card,
            email=thing.email,
            image=thing.image,
            image_alt=thing.image_alt,
            operation_hours=thing.operation_hours,
            created_at=thing.created_at,
            updated_at=thing.updated_at,

            things_page=True,
            places_page=False,
        )
        
        # M2M: FilterTypes (reuse existing)
        for ft in thing.filter_type_list.using(db_alias).all():
            resource.filter_type_list.add(ft)

        # M2M: FilterSubTypes (reuse existing)
        for fst in thing.filter_subtype_list.using(db_alias).all():
            resource.filter_subtype_list.add(fst)
            
    # -----------------------------
    # 2. MIGRATE PLACES → RESOURCES
    # -----------------------------
    for place in Place.objects.using(db_alias).all():
        resource = Resource.objects.using(db_alias).create(
            name=place.name,
            slug=place.slug,
            featured=place.featured,
            description=place.description,
            address=place.address,
            city=place.city,
            state='MO',
            phone_number=place.phone_number,
            external_website=place.external_website,
            internal_page=place.internal_page,
            custom_card=True,  # Place all has custom cards
            email=place.email,
            image=place.image,
            image_alt=place.image_alt,
            operation_hours=place.operation_hours,
            created_at=place.created_at,
            updated_at=place.updated_at,

            things_page=False,
            places_page=True,
        )

        # M2M: FilterTypes
        for ft in place.filter_type_list.using(db_alias).all():
            resource.filter_type_list.add(ft)

        # M2M: FilterSubTypes
        for fst in place.filter_subtype_list.using(db_alias).all():
            resource.filter_subtype_list.add(fst)
            
def reverse_migrate_data(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Resource = apps.get_model('resources', 'Resource')

    # Remove all migrated resources
    Resource.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_resource_custom_card_resource_image_alt_and_more'),
        ('things', '0011_thing_custom_card'),
        ('places', '0006_place_image_alt'),
    ]

    operations = [
        migrations.RunPython(migrate_data, reverse_migrate_data),
    ]